import { Response } from 'express';
import fs from 'fs';
import path from 'path';
import { base, TABLES } from '../config/airtable';
import { AuthRequest } from '../middlewares/auth';
import { buildSafeFilterFormula } from '../utils/airtableHelpers';
import { extractPdfData } from '../utils/peppolAnalyzer/extractPdf';
import { extractExcelData } from '../utils/peppolAnalyzer/extractExcel';
import { validatePeppolRules } from '../utils/peppolAnalyzer/validate';
import { calculateConformityScore } from '../utils/peppolAnalyzer/score';
import { generatePeppolUBL } from '../utils/peppolAnalyzer/generateUbl';

/**
 * Register an uploaded invoice in Airtable
 * POST /api/invoices
 */
export const registerUploadedInvoice = async (req: AuthRequest, res: Response) => {
  try {
    const userId = req.userId!;
    const { fileName, fileUrl, status, conformityScore, errorsList, errorsData, xmlFilename, ublFileUrl } = req.body;

    // Validate required fields
    if (!fileName || !fileUrl) {
      return res.status(400).json({ error: 'fileName and fileUrl are required' });
    }

    // Validate status
    const validStatuses = ['uploaded', 'checked', 'converted', 'sent'];
    if (status && !validStatuses.includes(status)) {
      return res.status(400).json({ 
        error: `Invalid status "${status}". Must be one of: uploaded, checked, converted, sent` 
      });
    }

    // Check user quota before creating invoice
    const user = await base(TABLES.USERS).find(userId);
    const quotaLimit = user.fields.quotaLimit !== undefined ? Number(user.fields.quotaLimit) : 1;
    const quotaUsed = user.fields.quotaUsed !== undefined ? Number(user.fields.quotaUsed) : 0;
    const isUnlimited = quotaLimit === -1;

    // Block if quota exceeded
    if (!isUnlimited && quotaUsed >= quotaLimit) {
      return res.status(403).json({ 
        error: `Quota limit reached. You have used ${quotaUsed}/${quotaLimit} uploads this month. Upgrade your plan to continue.` 
      });
    }

    // Create invoice record in Airtable
    // Try to save with all fields, fallback gracefully if some fields don't exist
    let records;
    try {
      records = await base(TABLES.INVOICES).create([
        {
          fields: {
            'User': [userId], // Link to Users table
            'File Name': fileName,
            'File URL': fileUrl,
            'Status': status || 'uploaded',
            'Conformity Score': conformityScore || 0,
            'Errors List': errorsList || '',
            'Errors Data': errorsData || '', // JSON string for i18n translation
            'XML Filename': xmlFilename || '', // Real XML filename for UBL download
            'UBL File URL': ublFileUrl || '', // Direct URL for UBL download
            // Note: 'Created At' is auto-generated by Airtable if it's a Created Time field
          },
        },
      ]);
    } catch (error: any) {
      // If new fields don't exist in Airtable, retry without them
      if (error.statusCode === 422 || error.message?.includes('INVALID_FIELD_NAME')) {
        console.log('⚠️  Some Airtable fields not found, saving in compatibility mode');
        records = await base(TABLES.INVOICES).create([
          {
            fields: {
              'User': [userId],
              'File Name': fileName,
              'File URL': fileUrl,
              'Status': status || 'uploaded',
              'Conformity Score': conformityScore || 0,
              'Errors List': errorsList || '',
              // New fields omitted - may not exist yet
            },
          },
        ]);
      } else {
        // Re-throw if it's a different error
        throw error;
      }
    }

    const invoice = records[0];

    // Increment quotaUsed after successful upload (only if not unlimited)
    if (!isUnlimited) {
      await base(TABLES.USERS).update(userId, {
        quotaUsed: quotaUsed + 1
      });
    }

    res.status(201).json({
      id: invoice.id,
      fileName: invoice.fields['File Name'],
      fileUrl: invoice.fields['File URL'],
      status: invoice.fields['Status'],
      conformityScore: invoice.fields['Conformity Score'],
      errorsList: invoice.fields['Errors List'],
      errorsData: invoice.fields['Errors Data'],
      xmlFilename: invoice.fields['XML Filename'],
      ublFileUrl: invoice.fields['UBL File URL'],
      createdAt: invoice.fields['Created At'],
    });
  } catch (error: any) {
    console.error('Register invoice error:', error);
    res.status(500).json({ error: 'Failed to register invoice' });
  }
};

/**
 * Get all invoices for the authenticated user
 * GET /api/invoices
 */
export const getInvoices = async (req: AuthRequest, res: Response) => {
  try {
    const userId = req.userId!;

    // Get all invoices and filter in code
    // Note: Airtable's linked record fields return arrays, so we can't use simple equality
    const records = await base(TABLES.INVOICES)
      .select({
        sort: [{ field: 'Created At', direction: 'desc' }],
      })
      .all();
    
    // Filter records where the User array includes the current userId
    const userRecords = records.filter(record => {
      const userIds = record.fields['User'] as string[] | undefined;
      return userIds && userIds.includes(userId);
    });

    const invoices = userRecords.map((record) => ({
      id: record.id,
      fileName: record.fields['File Name'],
      fileUrl: record.fields['File URL'],
      status: record.fields['Status'],
      conformityScore: record.fields['Conformity Score'],
      errorsList: record.fields['Errors List'],
      errorsData: record.fields['Errors Data'],
      xmlFilename: record.fields['XML Filename'],
      ublFileUrl: record.fields['UBL File URL'],
      createdAt: record.fields['Created At'],
    }));

    res.json({ invoices, count: invoices.length });
  } catch (error) {
    console.error('Get invoices error:', error);
    res.status(500).json({ error: 'Failed to fetch invoices' });
  }
};

/**
 * Analyze an uploaded invoice with Peppol engine
 * POST /api/invoices/analyze
 */
export const analyzeInvoice = async (req: AuthRequest, res: Response) => {
  console.log('🔵 [ANALYZE] Fonction analyzeInvoice appelée');
  console.log('🔵 [ANALYZE] req.file:', req.file ? req.file.filename : 'UNDEFINED');
  console.log('🔵 [ANALYZE] req.body:', JSON.stringify(req.body));
  
  try {
    if (!req.file) {
      console.error('🔴 [ANALYZE] Pas de fichier uploadé!');
      return res.status(400).json({ error: 'No file uploaded' });
    }

    const filePath = req.file.path;
    const fileType = req.file.mimetype;
    console.log('🔵 [ANALYZE] filePath:', filePath);
    console.log('🔵 [ANALYZE] fileType:', fileType);
    
    // 1. Extraction selon type
    let invoiceData;
    console.log('🔵 [ANALYZE] Étape 1: Extraction...');
    if (fileType === 'application/pdf') {
      invoiceData = await extractPdfData(filePath);
    } else if (fileType.includes('spreadsheet') || fileType.includes('excel')) {
      invoiceData = extractExcelData(filePath);
    } else {
      console.error('🔴 [ANALYZE] Type de fichier non supporté:', fileType);
      return res.status(400).json({ error: 'Type de fichier non supporté. Utilisez PDF ou Excel.' });
    }
    console.log('🔵 [ANALYZE] Données extraites:', JSON.stringify(invoiceData).substring(0, 200));
    
    // 2. Validation
    console.log('🔵 [ANALYZE] Étape 2: Validation...');
    const validationResults = validatePeppolRules(invoiceData);
    console.log('🔵 [ANALYZE] Résultats validation:', validationResults.length, 'règles');
    
    // 3. Score
    console.log('🔵 [ANALYZE] Étape 3: Calcul du score...');
    const score = calculateConformityScore(validationResults);
    console.log('🔵 [ANALYZE] Score:', score);
    
    // 4. Génération UBL
    console.log('🔵 [ANALYZE] Étape 4: Génération UBL...');
    let ublXml = '';
    let xmlFilename = '';
    
    try {
      console.log('🔵 [ANALYZE] Appel generatePeppolUBL...');
      ublXml = generatePeppolUBL(invoiceData);
      console.log('🔵 [ANALYZE] XML généré, longueur:', ublXml.length, 'caractères');
      
      // Calculer le nom XML SANS double extension (.pdf.xml → .xml)
      const originalFilename = req.file.filename;
      const extname = path.extname(originalFilename); // ".pdf" ou ".xlsx"
      const baseFilename = originalFilename.replace(extname, ''); // "invoice-123456789"
      xmlFilename = `${baseFilename}.xml`; // "invoice-123456789.xml"
      console.log('🔵 [ANALYZE] xmlFilename calculé:', xmlFilename);
      
      // ⚠️ IMPORTANT: Sur Render (plan gratuit), le filesystem est éphémère!
      // On stocke le contenu XML directement dans Airtable au lieu du disque
      
      // Mise à jour Airtable avec le contenu UBL complet
      const { invoiceId } = req.body;
      console.log('🔵 [ANALYZE] invoiceId pour update Airtable:', invoiceId);
      
      if (invoiceId) {
        // ⭐ ÉTAPE 1: Sauvegarder le UBL Content EN PREMIER (priorité absolue)
        console.log('🔵 [ANALYZE] Étape 4a: Sauvegarde UBL Content dans Airtable...');
        try {
          await base(TABLES.INVOICES).update(invoiceId, {
            'UBL Content': ublXml,
            'XML Filename': xmlFilename,
            'UBL File URL': `/api/invoices/download-ubl/${invoiceId}`,
          });
          console.log(`✅ [ANALYZE] UBL Content sauvegardé pour invoice ${invoiceId} (${ublXml.length} caractères)`);
        } catch (ublSaveError: any) {
          console.error('🔴 [ANALYZE] ERREUR sauvegarde UBL Content:', ublSaveError.message);
          console.error('🔴 [ANALYZE] Code erreur:', ublSaveError.statusCode);
          // Ne pas abandonner - continuer avec les autres champs
        }
        
        // ⭐ ÉTAPE 2: Mettre à jour les autres champs (score, status, etc.)
        console.log('🔵 [ANALYZE] Étape 4b: Mise à jour des métadonnées...');
        try {
          await base(TABLES.INVOICES).update(invoiceId, {
            'Conformity Score': score,
            'Status': 'UBL Generated',
          });
          console.log(`✅ [ANALYZE] Score ${score}% et Status mis à jour pour invoice ${invoiceId}`);
        } catch (metaError: any) {
          console.error('⚠️ [ANALYZE] Erreur mise à jour métadonnées:', metaError.message);
        }
        
        // ⭐ ÉTAPE 3: Mettre à jour les champs optionnels (peuvent ne pas exister)
        console.log('🔵 [ANALYZE] Étape 4c: Mise à jour des champs optionnels...');
        try {
          await base(TABLES.INVOICES).update(invoiceId, {
            'Invoice Number': invoiceData.invoiceNumber || '',
            'Invoice Date': invoiceData.issueDate || '',
            'Total Amount': invoiceData.totals?.grossAmount || 0,
          });
          console.log(`✅ [ANALYZE] Champs optionnels mis à jour pour invoice ${invoiceId}`);
        } catch (optionalError: any) {
          // Ces champs sont optionnels, on ignore les erreurs
          console.log('⚠️ [ANALYZE] Champs optionnels non mis à jour (normal si non existants)');
        }
        
      } else {
        console.log('⚠️ [ANALYZE] Pas de invoiceId fourni, pas de mise à jour Airtable');
      }
    } catch (ublError: any) {
      console.error('🔴 [ANALYZE] ERREUR dans bloc génération UBL:', ublError);
      console.error('🔴 [ANALYZE] Stack trace:', ublError?.stack);
    }
    
    console.log('🔵 [ANALYZE] Étape 5: Envoi réponse...');
    console.log('🔵 [ANALYZE] xmlFilename final:', xmlFilename || 'NULL');
    
    // Récupérer invoiceId pour la réponse
    const responseInvoiceId = req.body.invoiceId;
    
    // 5. Réponse avec le vrai nom du fichier XML et l'URL basée sur invoiceId
    res.json({
      success: true,
      score,
      errors: validationResults.filter(v => v.severity === 'error'),
      warnings: validationResults.filter(v => v.severity === 'warning'),
      xmlFilename: xmlFilename || null,
      ublFileUrl: responseInvoiceId ? `/api/invoices/download-ubl/${responseInvoiceId}` : null,
      extractedData: invoiceData
    });
    
  } catch (error: any) {
    console.error('🔴 [ANALYZE] ERREUR GLOBALE:', error);
    console.error('🔴 [ANALYZE] Stack:', error?.stack);
    res.status(500).json({ 
      success: false, 
      error: 'Erreur lors de l\'analyse de la facture' 
    });
  }
};

/**
 * Delete an invoice
 * DELETE /api/invoices/:id
 */
export const deleteInvoice = async (req: AuthRequest, res: Response) => {
  try {
    const userId = req.userId!;
    const { id } = req.params;

    // First, fetch the record to verify ownership
    const record = await base(TABLES.INVOICES).find(id);

    // Check if the user owns this invoice
    // The 'User' field is an array of user IDs (linked record)
    const userIds = record.fields['User'] as string[];
    if (!userIds || !userIds.includes(userId)) {
      return res.status(403).json({ error: 'Access denied to this invoice' });
    }

    // Delete the invoice
    await base(TABLES.INVOICES).destroy([id]);

    res.json({ message: 'Invoice deleted successfully' });
  } catch (error: any) {
    console.error('Delete invoice error:', error);
    
    if (error.statusCode === 404 || error.message?.includes('NOT_FOUND')) {
      return res.status(404).json({ error: 'Invoice not found' });
    }
    
    res.status(500).json({ error: 'Failed to delete invoice' });
  }
};
